module DappInterface.Terms exposing (view)

import CompoundComponents.Utils.CompoundHtmlAttributes exposing (HrefLinkType(..), class, href, id, type_)
import Html exposing (Html, a, b, div, h2, h4, label, li, ol, p, section, span, text, u)
import Strings.Terms as Terms
import Strings.Translations as Translations


view : Translations.Lang -> Html msg
view userLanguage =
    div [ id "terms" ]
        [ section [ class "hero" ]
            [ div [ class "container" ]
                [ label [ class "label big" ] [ text (Terms.terms_updated_date userLanguage) ]
                , h2 [] [ text (Terms.terms_of_service userLanguage) ]
                , p [] [ text (Terms.terms_intro_part1 userLanguage) ]
                , p []
                    [ text (Terms.terms_intro_part2 userLanguage)
                    , b [] [ text (Terms.terms_intro_part3 userLanguage) ]
                    , text (Terms.terms_intro_part4 userLanguage)
                    ]
                ]
            ]
        , section [ id "terms-items" ]
            [ div [ class "container" ]
                [ div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_1_header userLanguage) ]
                    , p [] [ text (Terms.terms_1_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_2_header userLanguage) ]
                    , p [] [ text (Terms.terms_2_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_3_header userLanguage) ]
                    , p [] [ text (Terms.terms_3_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_4_header userLanguage) ]
                    , p [] [ text (Terms.terms_4_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_5_header userLanguage) ]
                    , p [] [ text (Terms.terms_5_description userLanguage) ]
                    , ol [ type_ "a" ]
                        [ li []
                            [ p []
                                [ u [] [ text (Terms.terms_5_bullet_a_title userLanguage) ]
                                , text ". "
                                , text (Terms.terms_5_bullet_a_descriptiopn userLanguage)
                                ]
                            ]
                        , li []
                            [ p []
                                [ u [] [ text (Terms.terms_5_bullet_b_title userLanguage) ]
                                , text ". "
                                , text (Terms.terms_5_bullet_b_descriptiopn userLanguage)
                                ]
                            ]
                        , li []
                            [ p []
                                [ u [] [ text (Terms.terms_5_bullet_c_title userLanguage) ]
                                , text ". "
                                , text (Terms.terms_5_bullet_c_descriptiopn userLanguage)
                                ]
                            ]
                        , li []
                            [ p []
                                [ u [] [ text (Terms.terms_5_bullet_d_title userLanguage) ]
                                , text ". "
                                , text (Terms.terms_5_bullet_d_descriptiopn userLanguage)
                                ]
                            ]
                        , li []
                            [ p []
                                [ u [] [ text (Terms.terms_5_bullet_e_title userLanguage) ]
                                , text ". "
                                , text (Terms.terms_5_bullet_e_descriptiopn userLanguage)
                                ]
                            ]
                        ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_6_header userLanguage) ]
                    , p [] [ text (Terms.terms_6_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_7_header userLanguage) ]
                    , p []
                        [ text (Terms.terms_7_description_part1 userLanguage)
                        , b [] [ text (Terms.terms_7_description_part2 userLanguage) ]
                        , text (Terms.terms_7_description_part3 userLanguage)
                        ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_8_header userLanguage) ]
                    , p [] [ text (Terms.terms_8_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_9_header userLanguage) ]
                    , p [] [ text (Terms.terms_9_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_10_header userLanguage) ]
                    , p []
                        [ text (Terms.terms_10_description_part1 userLanguage)
                        , b [] [ text (Terms.terms_10_description_part2 userLanguage) ]
                        ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_11_header userLanguage) ]
                    , p [] [ text (Terms.terms_11_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_12_header userLanguage) ]
                    , p [] [ text (Terms.terms_12_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_13_header userLanguage) ]
                    , p [] [ text (Terms.terms_13_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_14_header userLanguage) ]
                    , p [] [ text (Terms.terms_14_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_15_header userLanguage) ]
                    , p [] [ text (Terms.terms_15_description_part1 userLanguage) ]
                    , p []
                        [ text (Terms.terms_15_description_part2 userLanguage)
                        , b [] [ text (Terms.terms_15_description_part3 userLanguage) ]
                        , text (Terms.terms_15_description_part4 userLanguage)
                        ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_16_header userLanguage) ]
                    , p [] [ text (Terms.terms_16_description userLanguage) ]
                    ]
                , div [ class "term-item" ]
                    [ h4 [] [ text (Terms.terms_17_header userLanguage) ]
                    , p [] [ text (Terms.terms_17_description userLanguage) ]
                    ]
                ]
            ]
        ]
